name: Build LaTeX document

on: [push]

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compile French CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: french.tex
          args: -pdf -jobname=cv_benjamin_collet.fr

      - name: Compile English CV
        uses: xu-cheng/latex-action@v2
        with:
          root_file: english.tex
          args: -pdf -jobname=cv_benjamin_collet.en

      - uses: actions/upload-artifact@v3
        with:
          path: "*.pdf"
